---
- name: Delete Auditd Rules Directory
  ansible.builtin.file:
    path: "{{ auditd_rules_dir }}"
    state: absent
  when:
    - auditd_manage_rules_directory

- name: Create Auditd Rules Directory
  ansible.builtin.file:
    path: "{{ auditd_rules_dir }}"
    state: directory
    mode: '0750'

- name: Configure the Auditd Rules
  ansible.builtin.template:
    src: "{{ item }}.rules.j2"
    dest: "{{ auditd_rules_dir }}/{{ item }}.rules"
    mode: '0644'
    backup: "{{ auditd_backup | default(false) }}"
  with_items: "{{ auditd_rules_templates }}"
  notify:
    - Augenrules
    - Restart auditd

- name: Configure /etc/audit/auditd.conf
  ansible.builtin.lineinfile:
    dest: /etc/audit/auditd.conf
    regexp: "{{ item.regex }}"
    line: "{{ item.line }}"
    mode: '0640'
  with_items: "{{ auditd_conf }}"
  notify:
    - Restart auditd

- name: Start and Enable auditd
  ansible.builtin.service:
    name: auditd
    state: started
    enabled: true
